# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b7vKvxxswHMrDTallVUgQio-L6mbihwS
"""

import ee
import geemap
ee.Authenticate()
ee.Initialize(project="my-project-332613")
m = geemap.Map()
landsat=ee.ImageCollection("LANDSAT/LC08/C02/T1_TOA")\
.filterDate('2022-01-01','2024-01-01')\
.filter(ee.Filter.lt('CLOUD_COVER',5))\
.median();
NDVI_EQ='B5 -B4 / (B5 + B4)'
ndvi_vis = {'min': 0, 'max': 0.5}
ndvi=landsat.expression(NDVI_EQ,{'B5':landsat.select("B5"),'B4':landsat.select('B4')}).rename('NDVI_1')
# or
NDVI_EQ2=landsat.select('B5').subtract(landsat.select('B4')).divide(landsat.select('B5').add(landsat.select('B4'))).rename('NDVI_2')
ndvi.getInfo()
NDVI_EQ2.getInfo()