# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vkq7-dxtAqdqXLvgkTyRolgGtRRFtzJL
"""

import ee
import geemap
ee.Authenticate()
ee.Initialize(project="my-project-332613")
Collection_1=ee.ImageCollection("LANDSAT/LC08/C02/T1_TOA")\
.filterDate('2018-01-01','2019-01-01')\
.filter(ee.Filter.lt('CLOUD_COVER',2))\
.median();
Collection_2=ee.ImageCollection("LANDSAT/LC08/C02/T1_TOA")\
.filterDate('2023-01-01','2024-01-01')\
.filter(ee.Filter.lt('CLOUD_COVER',2))\
.median();
# Calculating NDWI MNDWI EVI
NDWI_EQ='B3 - B5/(B3 + B5)'
B3_Col_1=Collection_1.select("B3")
B3_Col_2=Collection_2.select("B3")
B5_Col_1=Collection_1.select("B5")
B5_Col_2=Collection_2.select("B5")
NDWI_Time1=Collection_1.expression(NDWI_EQ,{'B3':B3_Col_1,'B5':B5_Col_1}).rename('NDWI');
NDWI_Time2=Collection_2.expression(NDWI_EQ,{'B3':B3_Col_2,'B5':B5_Col_2}).rename('NDWI');
# MNDWI Index
B6_Col_1=Collection_1.select("B6")
B6_Col_2=Collection_2.select("B6")
MNDWI_EQ='B3 - B6 /(B3 + B6)'
MNDWI_Time1=Collection_1.expression(MNDWI_EQ,{'B3':B3_Col_1,'B6':B6_Col_1}).rename('MNDWI');
MNDWI_Time2=Collection_2.expression(MNDWI_EQ,{'B3':B3_Col_2,'B6':B6_Col_2}).rename('MNDWI');
# EVI
B4_Col_2=Collection_2.select("B4")
B4_Col_1=Collection_1.select("B4")
B2_Col_1=Collection_1.select("B2")
B2_Col_2=Collection_2.select("B2")
evi_Time_1=(B5_Col_1.subtract(B4_Col_1)).multiply(2.5).divide(B5_Col_1.add(B4_Col_1.multiply(6)).subtract((B2_Col_1.add(1)).multiply(7.5).add(1)))
evi_Time_2=(B5_Col_2.subtract(B4_Col_2)).multiply(2.5).divide(B5_Col_2.add(B4_Col_2.multiply(6)).subtract((B2_Col_2.add(1)).multiply(7.5).add(1)))